<a href="https://colab.research.google.com/github/Soumadeep10/RINEX-ML/blob/main/D4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#16th May 2022

In [ ]:
#while
#print numbers from 0 to 9 using while loop

In [3]:
a = 0
while(a<10):
  print(a)
  a = a+1

0
1
2
3
4
5
6
7
8
9


In [4]:
a = 0
while(a<10):
  print(a,end = '')
  a = a+1

0123456789

In [5]:
a = 0
while(a<10):
  print(a,end = ' ')
  a = a+1

0 1 2 3 4 5 6 7 8 9 

In [7]:
a = 0
while(a<10):
  print(a,end = ' ')
  a = a+2 # or a+=2

0 2 4 6 8 

In [10]:
#Create a multiplication Table using while
i = 1
n = 15
while(i<=10):
  print(n, "*" ,i, "=",n*i)
  i = i+1

15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [12]:
#CONDITIONAL STATEMENTS - IF, IF-ELSE, ELIF
#WAP to check if the given number is odd or even
a = 10
if(a%2 == 0):
  print('Number is even')
else:
  print('Number is Odd')

Number is even


In [13]:
a = input('Enter the Weather condition:')
if(a == 'Summer'):
  print('It is Summer Season')
if(a =='Winter'):
  print('It is Winter Season')
if(a == 'Monsoon'):
  print('It is Rainy season')
else:
  print('Invalid input')

Enter the Weather condition:Summer
It is Summer Season
Invalid input


In [14]:
a = input('Enter the Weather condition:')
if(a == 'Summer'):
  print('It is Summer Season')
elif(a =='Winter'):
  print('It is Winter Season')
elif(a == 'Monsoon'):
  print('It is Rainy season')
else:
  print('Invalid input')

Enter the Weather condition:Summer
It is Summer Season


In [16]:
while True:
  a = input('Enter the Weather condition:')
  if(a == 'Summer'):
    print('It is Summer Season')
  elif(a =='Winter'):
    print('It is Winter Season')
  elif(a == 'Monsoon'):
    print('It is Rainy season')
  else:
    print('Invalid input')

Enter the Weather condition:Summer
It is Summer Season
Enter the Weather condition:Winter
It is Winter Season
Enter the Weather condition:Monsoon
It is Rainy season
Enter the Weather condition:cold
Invalid input


KeyboardInterrupt: ignored

In [ ]:
#SEQUENCES IN PYTHON
#Sequences are containers where we can store different items
#In arrays we can store elements of only one data type, but here in sequences, multiple datatypes are used.
#Lists, Tuple, Sets, Dictionary



In [18]:
#LISTS [] - ordered and mutable(the elements of lists can be changed) 
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [19]:
type(a)

list

In [20]:
fruits = ['Mango','Apple','Grapes']
fruits

['Mango', 'Apple', 'Grapes']

In [24]:
fruits.append('Banana') #It will add/insert new element in the list

In [25]:
print(fruits)

['Mango', 'Apple', 'Grapes', 'banana', 'Banana']


In [30]:
fruits.insert(2,'Orange') #It will add a new element at index number 2

In [31]:
print(fruits)

['Mango', 'Apple', 'Orange', 'Grapes', 'grapes', 'Grapes', 'banana', 'Banana']


In [32]:
fruits.remove('Grapes')# It will remove the element from the list

In [34]:
print(fruits)

['Mango', 'Apple', 'Orange', 'grapes', 'Grapes', 'banana', 'Banana']


In [35]:
fruits.pop(3) #Removing elementd based on index


'grapes'

In [36]:
print(fruits)

['Mango', 'Apple', 'Orange', 'Grapes', 'banana', 'Banana']


In [37]:
fruits.reverse()#It will reverse the lists

In [38]:
print(fruits)

['Banana', 'banana', 'Grapes', 'Orange', 'Apple', 'Mango']


In [40]:
#TUPLE - () - ORDERED,IMMUTABLE(Cannot be changed by opperation on Tuple)
b = (1,2,3.0,0,True,'HELLO WORLD')
b

(1, 2, 3.0, 0, True, 'HELLO WORLD')

In [41]:
type(b)

tuple

In [42]:
b.insert(2,'orange') #So tuples are immutable

AttributeError: ignored

In [43]:
#SET - {} - SETS ARE UNORDERED
c = {1,2,3,4,5,6,7,8,9,10}
type(c)

set

In [44]:
d = {5,6,7,8,9,10,11,12,13,14}
d

{5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

In [45]:
c

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [46]:
#UNION OF SETS
c | d

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

In [47]:
#INTERSECTION OF TWO SETS
c & d

{5, 6, 7, 8, 9, 10}

In [48]:
#DICTIONARY - {key :value,key :value} - Unordered
data = {1 :'Python',2 :'Java',3 :'C++'}
data 

{1: 'Python', 2: 'Java', 3: 'C++'}

In [49]:
type(data)

dict

In [50]:
cars = {'Brand' :['Maruti','Ford','Volvo'],'Passings':[3,7,19]}
print(cars)

{'Brand': ['Maruti', 'Ford', 'Volvo'], 'Passings': [3, 7, 19]}


In [51]:
type(cars)

dict

In [ ]:
#PYTHON LIBRARIES -  COLLECTION OF MODULES
#NUMPY, PANDAS, MATPLOTLIB, SKLEAR

In [ ]:
#NUMPY - NUMERICAL PYTHON 
#It is used instead of list- To store data
#NUMPY are efficient snd much more faster than lists


In [52]:
import numpy as np #np is the abbreviation of numpy
a = np.array(1) #scalar - 0 dimenssional
a

array(1)

In [53]:
type(a) #nd means n dimensional array

numpy.ndarray

In [54]:
a.size #total number of elements in an array

1

In [55]:
a.shape #no.of rows and colums(0 here in this case)

()

In [56]:
a.ndim #.ndim tells us the dimenssion of the array

0

In [58]:
b = np.array([1,2,3,4,5]) #vectors - 1 dimensional
b

array([1, 2, 3, 4, 5])

In [59]:
b.shape #(5,) - means 5 coloums and 1 row
#in 1D array its(colums,row)

(5,)

In [60]:
b.size #no.of elements inside the array

5

In [62]:
b.ndim #dimenssion

1

In [64]:
c = np.array([[1,2,3],[4,5,6]]) # matrix - 2 dimension
#in 2D its(rows,cols)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
c.size

6

In [66]:
c.shape #(2,3) - means 2 rows 3 coloums

(2, 3)

In [70]:
#np - numpy,random - package(collection of libraries),randint -Library
np.random.seed(69) #if i want to keep the generated value constant, I use np.random.seed()
d = np.random.randint(0,10,10) #I want 10 random Integers into the range of 1 to 10 
d

array([6, 9, 7, 4, 1, 6, 9, 8, 1, 6])

In [71]:
d.size

10

In [72]:
d.shape

(10,)

In [77]:
d.reshape(5,2) #reshape possibilites: (5,2),(2,5) and (10,1)

array([[6, 9],
       [7, 4],
       [1, 6],
       [9, 8],
       [1, 6]])

In [74]:
d

array([6, 9, 7, 4, 1, 6, 9, 8, 1, 6])

In [78]:
x = np.ones(10) #np.ones is for white colours-(255)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
x.dtype

dtype('float64')

In [80]:
y = np.zeros(69) #np.zeros is for black colours-(0)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
#Digital - 2 States - On/Off,High/Low,True/False,1/0
#in numpy, I've got the range in between o to 255
#0 - Black
#255- White